// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkopyae2Do9yrLTs6pjChBHndXSb4oPsU',
    appId: '1:822717734012:web:31fd57bb925e663a95fdf9',
    messagingSenderId: '822717734012',
    projectId: 'beast-training-app',
    authDomain: 'beast-training-app.firebaseapp.com',
    storageBucket: 'beast-training-app.firebasestorage.app',
    measurementId: 'G-PJ01T0PDSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5wlY-I3BmqqKaqHqUPmISPoPG5BgyIDk',
    appId: '1:822717734012:android:e4d05d8af56352d595fdf9',
    messagingSenderId: '822717734012',
    projectId: 'beast-training-app',
    storageBucket: 'beast-training-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW4vrRqWyS-7FgQxZV-W40-tgltmDnSfQ',
    appId: '1:822717734012:ios:5f7a4bdd226d026695fdf9',
    messagingSenderId: '822717734012',
    projectId: 'beast-training-app',
    storageBucket: 'beast-training-app.firebasestorage.app',
    iosBundleId: 'com.example.beastTraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW4vrRqWyS-7FgQxZV-W40-tgltmDnSfQ',
    appId: '1:822717734012:ios:5f7a4bdd226d026695fdf9',
    messagingSenderId: '822717734012',
    projectId: 'beast-training-app',
    storageBucket: 'beast-training-app.firebasestorage.app',
    iosBundleId: 'com.example.beastTraining',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkopyae2Do9yrLTs6pjChBHndXSb4oPsU',
    appId: '1:822717734012:web:428697569f2d65c495fdf9',
    messagingSenderId: '822717734012',
    projectId: 'beast-training-app',
    authDomain: 'beast-training-app.firebaseapp.com',
    storageBucket: 'beast-training-app.firebasestorage.app',
    measurementId: 'G-L2EY08ECPG',
  );
}
